// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCxJ8PITLlsdTWvZ-niAiRW1K2RIoy6sE',
    appId: '1:354818847275:web:65e9afe56e9e35928df06e',
    messagingSenderId: '354818847275',
    projectId: 'fir-chatapp-e2ebc',
    authDomain: 'fir-chatapp-e2ebc.firebaseapp.com',
    storageBucket: 'fir-chatapp-e2ebc.appspot.com',
    measurementId: 'G-M5X7FDPPRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1IduqeDJKZeNEuQxLTc0Q5mRkx1936wg',
    appId: '1:354818847275:android:3d954e1f59944fe38df06e',
    messagingSenderId: '354818847275',
    projectId: 'fir-chatapp-e2ebc',
    storageBucket: 'fir-chatapp-e2ebc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxSp1IXiVAFvyDg2DpkSuJBEoiSambjDk',
    appId: '1:354818847275:ios:d5fd09875990356a8df06e',
    messagingSenderId: '354818847275',
    projectId: 'fir-chatapp-e2ebc',
    storageBucket: 'fir-chatapp-e2ebc.appspot.com',
    iosBundleId: 'com.example.firbasseChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxSp1IXiVAFvyDg2DpkSuJBEoiSambjDk',
    appId: '1:354818847275:ios:6cabf57a7b8110748df06e',
    messagingSenderId: '354818847275',
    projectId: 'fir-chatapp-e2ebc',
    storageBucket: 'fir-chatapp-e2ebc.appspot.com',
    iosBundleId: 'com.example.firbasseChatapp.RunnerTests',
  );
}
